language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4.0'
  - '4.1'

cache:
  directories:
    - node_modules

notifications:
  email:
    - jeremie.drouet@gmail.com

before_script:
  - npm install

script:
  - npm test
